# Generated by Django 6.0.1 on 2026-01-25 11:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Staff ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('date_of_hire', models.DateField(blank=True, null=True, verbose_name='Date of Hire')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('status', models.CharField(choices=[('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('DRIVER', 'Driver'), ('ADMINISTRATIVE ASSISTANT', 'Administrative Assistant'), ('PHOTOGRAPHER', 'Photographer'), ('INTERN', 'Intern'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Position/Status')),
                ('ssnit_number', models.CharField(blank=True, max_length=50, verbose_name='SSNIT #')),
                ('ghana_card', models.CharField(blank=True, max_length=50, verbose_name='Ghana Card')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('bank_branch', models.CharField(blank=True, max_length=100, verbose_name='Branch')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='Contact/Phone')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('bmc', models.CharField(blank=True, help_text='Business Management Center', max_length=100, verbose_name='BMC')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Unit')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Grade')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Level')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monthly Basic Salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
    ]
