# Generated by Django 6.0.1 on 2026-02-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_config', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_config',
            field=models.ForeignKey(blank=True, help_text='Employee position from dynamic configuration', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core_config.employeeposition', verbose_name='Position (Dynamic)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('DRIVER', 'Driver'), ('ADMINISTRATIVE ASSISTANT', 'Administrative Assistant'), ('PHOTOGRAPHER', 'Photographer'), ('INTERN', 'Intern'), ('OTHER', 'Other')], help_text='Legacy status field - will be deprecated', max_length=50, null=True, verbose_name='Position/Status (Legacy)'),
        ),
    ]
