# Generated by Django 6.0.1 on 2026-02-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_employee_email_employee_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='separated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Separated At'),
        ),
        migrations.AddField(
            model_name='employee',
            name='separated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separated_employees', to=settings.AUTH_USER_MODEL, verbose_name='Separated By'),
        ),
        migrations.AddField(
            model_name='employee',
            name='separation_reason',
            field=models.TextField(blank=True, verbose_name='Separation Reason'),
        ),
    ]
