# Generated by Django 6.0.1 on 2026-02-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_config',
            field=models.ForeignKey(blank=True, help_text="User's role in the system (dynamic configuration)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core_config.userrole', verbose_name='Role (Dynamic)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('hr_admin', 'HR Admin'), ('hr_staff', 'HR Staff')], help_text='Legacy role field - will be deprecated', max_length=15, null=True),
        ),
    ]
