# Generated by Django 6.0.1 on 2026-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role_config_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, help_text='Department this system user belongs to', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, help_text='System user grade level', max_length=50, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, help_text='System user level', max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(blank=True, help_text='System User ID (distinct from Casual Employee Staff ID)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unit',
            field=models.CharField(blank=True, help_text='Organizational unit', max_length=100, verbose_name='Unit'),
        ),
    ]
