# Generated by Django 5.0.14 on 2026-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_bmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('hr_admin', 'HR Admin'), ('finance', 'Finance')], help_text='Legacy role field - will be deprecated', max_length=15, null=True),
        ),
    ]
