# Generated by Django 6.0.1 on 2026-01-25 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='e.g., Jan-2026', max_length=20, verbose_name='Month/Year')),
                ('agency', models.CharField(default='National Ambulance Service', max_length=200, verbose_name='Agency')),
                ('district', models.CharField(default='Accra Metropolitan Assembly', max_length=200, verbose_name='District')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('bmc', models.CharField(blank=True, help_text='Business Management Center', max_length=100, verbose_name='BMC')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Unit')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Grade')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Level')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Salary')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Allowances')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Salary')),
                ('ssnit_deduction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SSNIT (5.5%)')),
                ('tier2_deduction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tier 2 (3.5%)')),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Income Tax')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Deductions')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Salary')),
                ('payment_mode', models.CharField(blank=True, max_length=200, verbose_name='Payment Mode')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Approval Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payslips', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='staff.employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_payslips', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-generated_at'],
                'unique_together': {('employee', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('payment', 'Payment'), ('deduction', 'Deduction')], max_length=20)),
                ('nature', models.CharField(max_length=200, verbose_name='Nature/Description')),
                ('hours_or_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hours/Original Amount')),
                ('rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rate %')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance/Amount')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Line Item',
                'verbose_name_plural': 'Payslip Line Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
