# Generated by Django 6.0.1 on 2026-02-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_config', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(default='National Ambulance Service', max_length=200)),
                ('default_district', models.CharField(default='Accra Metropolitan Assembly', max_length=200)),
                ('ssnit_rate', models.DecimalField(decimal_places=2, default=5.5, help_text='Default SSNIT Rate (%)', max_digits=5)),
                ('tier2_rate', models.DecimalField(decimal_places=2, default=3.5, help_text='Default Tier 2 Rate (%)', max_digits=5)),
                ('default_bank_name', models.CharField(default='Ghana Commercial Bank', max_length=100)),
                ('default_bank_branch', models.CharField(default='Ministries', max_length=100)),
                ('agency_logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='status_config',
            field=models.ForeignKey(blank=True, help_text='Approval status from dynamic configuration', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='core_config.approvalstatus', verbose_name='Approval Status (Dynamic)'),
        ),
        migrations.AddField(
            model_name='paysliplineitem',
            name='deduction_type',
            field=models.ForeignKey(blank=True, help_text='Deduction type (if this is a deduction)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='core_config.deductiontype'),
        ),
        migrations.AddField(
            model_name='paysliplineitem',
            name='payment_type',
            field=models.ForeignKey(blank=True, help_text='Payment type (if this is a payment)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='core_config.paymenttype'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='agency',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Legacy approval status field - will be deprecated', max_length=10, null=True, verbose_name='Approval Status (Legacy)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='district',
            field=models.CharField(blank=True, max_length=200, verbose_name='District'),
        ),
    ]
