# Generated by Django 6.0.1 on 2026-02-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_systemconfiguration_payslip_status_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_bank_branch',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_bank_name',
        ),
    ]
