# Generated by Django 6.0.1 on 2026-02-06 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the status', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the status', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_approved_state', models.BooleanField(default=False, help_text='Does this status mean approved?')),
                ('is_rejected_state', models.BooleanField(default=False, help_text='Does this status mean rejected?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approval Status',
                'verbose_name_plural': 'Approval Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the BMC', max_length=50, unique=True)),
                ('name', models.CharField(help_text='BMC name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BMC',
                'verbose_name_plural': 'BMCs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the deduction type', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Deduction type name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_statutory', models.BooleanField(default=False, help_text='Is this a statutory deduction (SSNIT, Tax, etc.)?')),
                ('default_rate_percent', models.DecimalField(decimal_places=2, default=0, help_text='Default rate % (if applicable)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deduction Type',
                'verbose_name_plural': 'Deduction Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the department', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Department name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the position', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the position', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Position',
                'verbose_name_plural': 'Employee Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the grade', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Grade name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the level', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Level name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the payment type', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Payment type name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=True, help_text='Is this payment subject to income tax?')),
                ('default_rate_percent', models.DecimalField(decimal_places=2, default=0, help_text='Default rate % (if applicable)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the unit', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Unit name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for the role', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the role', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of this role's purpose")),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can create/edit/delete users')),
                ('can_manage_employees', models.BooleanField(default=False, help_text='Can create/edit/delete employees')),
                ('can_generate_payslips', models.BooleanField(default=False, help_text='Can generate payslips')),
                ('can_approve_payslips', models.BooleanField(default=False, help_text='Can approve/reject payslips')),
                ('can_view_all_payslips', models.BooleanField(default=False, help_text='Can view all payslips')),
                ('can_edit_configuration', models.BooleanField(default=False, help_text='Can edit system configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['name'],
            },
        ),
    ]
